project:
  type: website

website:
  title: "Predicting the next recession by relationship between Brent Oil Prices and US recession."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - model.qmd
      - about.qmd
      - sources.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



